### ISSUE TITLE
ssh and RDP via MyAP

### ISSUE THREAD

**Issue by HenriApperloo** [lukicdarkoo/rpi-wifi#2]
Hello,

I have install your script it works fantasic ! Thanks!

I can connect to MyAP en I receive the correct ip and gateway etc. Now I will connect with ssh or rdp from my laptop. It works good before I install your script. Must I add someware the interface that he will listen on the new interface ?

regards,
Henri Apperloo

**Comment by alectrocute** [comment]
I'm really late to this, don't know why nobody responded. Calling @lukicdarkoo?

Are you connecting to the ap0 access point? If so, make sure you use the router IP for ssh, eg. `ssh pi@192.168.10.1`.

**Comment by lukicdarkoo** [comment]
@HenriApperloo, do you still have the issue? Does the proposal by @alectrocute help you?
