### ISSUE TITLE
WLAN0 is not staying connected

### ISSUE THREAD

**Issue by aidbish** [lukicdarkoo/rpi-wifi#6]
Used the script and installed without issue. my AP comes up and can connect and is stable.
issue seems to be wlan0 dropping, it stays up for say 30 seconds then drops then comes back again after period of time

any ideas

**Comment by lukicdarkoo** [comment]
Can you provide more details, version of Raspberry Pi, version of Raspbian etc?

**Comment by neilyoung** [comment]
Having the same issue here. The disconnection after  - yes maybe 30 secs - can be seen in dmesg. Running RPI3B+ Raspbian Buster Lite.

The same script runs fine on a PiZero W
