### ISSUE TITLE
Feature Request: Accept a list of clients from file

### ISSUE THREAD

**Issue by BinaryShrub** [lukicdarkoo/rpi-wifi#9]
Thinking about using this for travel, it would be great if I could continue to append to a file and collect clients over time and have the script attempt to connect to them in order so I don't have to configure it as I move it around

**Comment by lukicdarkoo** [comment]
I think it is very specific to the use-case, I would rather create independent script running in parallel. You can add more clients simply by populating `/etc/wpa_supplicant/wpa_supplicant.conf` with new networks.

**Comment by BinaryShrub** [comment]
It doesn't seem very specific to me? Anyone who is traveling and using hotel wifi would use this; I think it'd still be a valuable add.
